STACK_NAME=$1
CURRENT_DIR="$STACK_LOCATION/$STACK_NAME"
ENABLE_FILE="$ROOT_DIR/enabled/$STACK_NAME"
ENABLE_LOCATION="$ROOT_DIR/enabled"

mkdir -p "$ENABLE_LOCATION"

if [ ! -f "$ENABLE_FILE" ]; then
  touch "$ENABLE_FILE"
fi
bash "$SCRIPT_DIR/single.sh" "$STACK_NAME" up -d
