REQUIRE_VAR "DOMAIN"
REQUIRE_VAR "EMAIL"
REQUIRE_VAR "LOCAL_IP"
REQUIRE_VAR "STACK_DATA"
REQUIRE_VAR "MEDIA_LOCATION"
REQUIRE_VAR "DATA_LOCATION"

ACME_FILE="$STACK_DATA/traefik/acme/acme.json"

if [ ! -f "$ACME_FILE" ]; then
  echo "{}" > "$ACME_FILE"
fi